export const animalOptions = [
  {
    label: "Cat",
    value: "cat",
    image: require("../../assets/images/animal/cat.png"),
    labelKey: "animal.cat",
  },
  {
    label: "Dog",
    value: "dog",
    image: require("../../assets/images/animal/dog.png"),
    labelKey: "animal.dog",
  },
  {
    label: "Rabbit",
    value: "rabbit",
    image: require("../../assets/images/animal/rabbit.png"),
    labelKey: "animal.rabbit",
  },
  {
    label: "Fish",
    value: "fish",
    image: require("../../assets/images/animal/fish.png"),
    labelKey: "animal.fish",
  },
  {
    label: "Bird",
    value: "bird",
    image: require("../../assets/images/animal/bird.png"),
    labelKey: "animal.bird",
  },
  {
    label: "Hamster",
    value: "hamster",
    image: require("../../assets/images/animal/hamster.png"),
    labelKey: "animal.hamster",
  },
];

export const PET_BREEDS = {
  cat: [
    { key: "persian" },
    { key: "siamese" },
    { key: "maineCoon" },
    { key: "ragdoll" },
    { key: "britishShorthair" },
    { key: "bengal" },
    { key: "sphynx" },
    { key: "abyssinian" },
    { key: "scottishFold" },
    { key: "burmese" },
    { key: "mixed" },
    { key: "americanShorthair" },
    { key: "norwegianForest" },
    { key: "siberian" },
    { key: "russianBlue" },
    { key: "exoticShorthair" },
    { key: "orientalShorthair" },
  ],
  dog: [
    { key: "labrador" },
    { key: "germanShepherd" },
    { key: "bulldog" },
    { key: "goldenRetriever" },
    { key: "beagle" },
    { key: "poodle" },
    { key: "rottweiler" },
    { key: "yorkshireTerrier" },
    { key: "dachshund" },
    { key: "doberman" },
    { key: "boxer" },
    { key: "shihTzu" },
    { key: "chihuahua" },
    { key: "pomeranian" },
    { key: "greatDane" },
  ],
  rabbit: [
    { key: "hollandLop" },
    { key: "netherlandDwarf" },
    { key: "lionhead" },
    { key: "miniRex" },
    { key: "flemishGiant" },
    { key: "newZealandRabbit" },
    { key: "californianRabbit" },
    { key: "dutchRabbit" },
    { key: "miniLop" },
    { key: "harlequinRabbit" },
    { key: "rexRabbit" },
    { key: "angoraRabbit" },
  ],
  fish: [
    { key: "betta" },
    { key: "goldfish" },
    { key: "guppy" },
    { key: "molly" },
    { key: "platy" },
    { key: "neonTetra" },
    { key: "angelfish" },
    { key: "cichlid" },
    { key: "koi" },
    { key: "discus" },
    { key: "swordtail" },
    { key: "gourami" },
  ],
  bird: [
    { key: "parrot" },
    { key: "canary" },
    { key: "budgerigar" },
    { key: "cockatiel" },
    { key: "lovebird" },
    { key: "africanGrey" },
    { key: "macaw" },
    { key: "finch" },
    { key: "cockatoo" },
    { key: "amazonParrot" },
  ],
  hamster: [
    { key: "syrianHamster" },
    { key: "campbellsDwarf" },
    { key: "winterWhite" },
    { key: "roborovski" },
    { key: "chineseHamster" },
  ],
};
