import type { MD3Typescale } from "react-native-paper/lib/typescript/types";

export const customTypography: MD3Typescale = {
  displayLarge: {
    fontFamily: "Alexandria_700Bold",
    fontWeight: "700",
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0.2,
  },
  displayMedium: {
    fontFamily: "Alexandria_600SemiBold",
    fontWeight: "600",
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0.15,
  },
  displaySmall: {
    fontFamily: "Alexandria_600SemiBold",
    fontWeight: "600",
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0.1,
  },
  headlineLarge: {
    fontFamily: "Alexandria_600SemiBold",
    fontWeight: "600",
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0.1,
  },
  headlineMedium: {
    fontFamily: "Alexandria_500Medium",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.1,
  },
  headlineSmall: {
    fontFamily: "Alexandria_500Medium",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: "Alexandria_600SemiBold",
    fontWeight: "600",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.15,
  },
  titleMedium: {
    fontFamily: "Alexandria_500Medium",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: "Alexandria_500Medium",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  bodyLarge: {
    fontFamily: "Alexandria_400Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontFamily: "Alexandria_400Regular",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: "Alexandria_300Light",
    fontWeight: "300",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  labelLarge: {
    fontFamily: "Alexandria_500Medium",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: "Alexandria_400Regular",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: "Alexandria_400Regular",
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.5,
  },
  default: {
    fontFamily: "Alexandria_400Regular",
    fontWeight: "400",
    letterSpacing: 0.25,
  },
};
